excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://samer290.github.io
title: All I Know About Python
email: samer.m.jabal@gmail.com
author: samer290
description: BullShit.
paginate: 7
google_analytics: 
